version: 2.1

executors:
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.52.0-noble
    resource_class: medium

jobs:
  checkout-and-setup:
    executor: playwright
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install-dependencies:
    executor: playwright
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  install-playwright:
    executor: playwright
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Playwright
          command: npx playwright install --with-deps
      - persist_to_workspace:
          root: .
          paths:
            - .

  install-mcp-server:
    executor: playwright
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Playwright MCP Server
          command: npm install @playwright/mcp@latest
      - persist_to_workspace:
          root: .
          paths:
            - .

  run-tests-and-upload:
    executor: playwright
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Playwright MCP Tests
          command: npm run mcp:headless
      - store_artifacts:
          path: cucumber-report.html
          destination: playwright-test-artifacts

workflows:
  version: 2
  playwright-mcp-tests:
    jobs:
      - checkout-and-setup
      - install-dependencies:
          requires:
            - checkout-and-setup
      - install-playwright:
          requires:
            - install-dependencies
      - install-mcp-server:
          requires:
            - install-playwright
      - run-tests-and-upload:
          requires:
            - install-mcp-server